# Generated by Django 5.0.4 on 2024-05-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20)),
                ('category', models.CharField(choices=[('Wages', 'Wages'), ('Other Income', 'Other Income'), ('Rent/Mortgage', 'Rent/Mortgage'), ('Groceries', 'Groceries'), ('Restaurants', 'Restaurants'), ('Insurance', 'Insurance'), ('Utilities', 'Utilities'), ('Gas', 'Gas'), ('Entertainment', 'Entertainment'), ('Loans', 'Loans')], max_length=20)),
                ('expected', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('difference', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
