# Generated by Django 5.0.4 on 2024-05-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Save_Money', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='end_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='savings_goals',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='start_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
