# Generated by Django 5.0.4 on 2024-05-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Save_Money', '0002_expense_end_balance_expense_savings_goals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='end_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
