# Generated by Django 5.0.4 on 2024-05-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Save_Money', '0004_alter_expense_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='month',
            field=models.CharField(max_length=20),
        ),
    ]
